# Generated by Django 4.2.1 on 2023-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0010_remove_allcourse_user_constraint_allstudent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allstudent",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
